### ISSUE TITLE
using those dotfiles on PC (without laptop) gives error

### ISSUE THREAD

**Issue by ahmed12345678910111213141516** [saimoomedits/dotfiles#32]
error messege:
~/.config/awesome/mods/battery-widget/init.lua:125: attempt to index a nil value (field 'device')
everything got build from the aur successfully
except xorg-init which couldn't bet found

**Comment by shaolingit** [comment]
yeah some for me for xorg-init it is xorg-xinit i think it is a typo . 
anyway i got the same problem on my laptop because my battery is BAT1 not BAT0 i tried everything but nothing worked i think to fix that on pc you have to remove the battery widget completely but i am new to awesome and idk how to :(

**Comment by sli-wka** [comment]
If you're on pc, go to ~/.config/awesome/signal/, open init.lua with a text editor and comment out the line "require("signal.battery")
