### ISSUE TITLE
local vol

### ISSUE THREAD

**Issue by CaptainKranch** [saimoomedits/dotfiles#9]
Hello,

I'm having the following errors:

1. **_Ugh, an error just occurred :(! concatenate a nill value local vol_**
2. Battery icons or brightens bar do not update unless I press ctrl + super + r
3. When battery is low, it spam notifications telling you this. I plugged the A/C adapter and it didn't stopped the notifications.

Am I doing something wrong? I fresh installed arch and followed your instructions :/ Also, the notifications when I use slack do not display the slack icon, is this normal or I have to hard-code this? I'm just wondering what is happening to check if I can fix it my self.

I really love this project, keep the great work!!

**Comment by saimoomedits** [comment]
hello, 
thanks for the feedback!

1. missing package
- the error occurs due to a missing package called `alsa-plugins`, I forgot to add the package in the setup
- you can install it by running `sudo pacman -S alsa-plugins`

2. another missing dependency :neutral_face: 
- yeah, the brightness also needs a package that I forgot to add in the setup, `inotify-tools`
- as for the battery icon, it uses  an `if` statement which updates at startup, I will try to fix it in the new commit.

3. My bad
- I have only added a function that will notify when batter is below 10 `value < 10`, so it notifies every-time the value changes and its below `10`, this will also be fixed in the new commit.

As for the slack icon, the notifications tries to display the image which the client is emitting, Slack probably doesn't emit any image. I am not a 100% sure.
 
if you need more help feel free to contact me on discord: No.#6972

lastly, thanks!
